### PR TITLE
Dev w1w2cofinancing

### PR DESCRIPTION
**Pull request by sebas932**

### CODE REVIEW

**Comment by sebas932** [comment]
image

**Comment by htobon** [comment]
Perhaps it will look better in two lines?

W/W2
Co-financing

**Comment by sebas932** [comment]
Implemented in budget by clusters of activities
image

**Comment by AndresFVR** [comment]
Pentaho reporting:

**Budget by partners**


**Budget by coas**

**Comment by sebas932** [comment]
Tooltip text in Budget by partners

**Comment by sebas932** [comment]
Budget types documented

**Pull request merged**
